enum LimitTypes {
    REFILL = 'REFILL',
    TURNOVER = 'TURNOVER',
    PAYMENTS_P2P = 'PAYMENTS_P2P',
    PAYMENTS_PROVIDER_INTERNATIONALS = 'PAYMENTS_PROVIDER_INTERNATIONALS',
    PAYMENTS_PROVIDER_PAYOUT = 'PAYMENTS_PROVIDER_PAYOUT',
    WITHDRAW_CASH = 'WITHDRAW_CASH',
}

export { LimitTypes }
